name: Build Image

on:
  pull_request:

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    name: Docker Image

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Publish image
        uses: docker/build-push-action@v6
        with:
          context: .
