name: Publish Image

on:
  push:
    branches:
      - main

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    name: Publish Docker

    # permissions:
    #   contents: write
    # permissions:
    #   packages: write

    environment:
      name: ghcr
      url: https://github.com/jwst-uncover/UNCOVER_DV_web/pkgs/container/uncover_dv

    steps:
      - name: Tag last commit 'latest'
        uses: EndBug/latest-tag@latest
        with:
          # You can change the name of the tag or branch with this input.
          # Default: 'latest'
          ref: latest

          # If a description is provided, the action will use it to create an annotated tag. If none is given, the action will create a lightweight tag.
          # Default: ''
          # description: Description for the tag

          # Force-update a branch instead of using a tag.
          # Default: false
          force-branch: true

          # Directory to use when executing git commands
          # Default: '${{ github.workspace }}'
          # git-directory: 'path/to/repo/dir'

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Define Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
        with:
          images: ghcr.io/jwst-uncover/uncover_dv
          tags: |
            type=raw,value=latest
            type=raw,value=${{ github.sha }}
          labels: |
            org.opencontainers.image.title="JWST Uncover"
            org.opencontainers.image.description="Web frontend for the JWST UNCOVER data viewer."
            org.opencontainers.image.url="https://github.com/jwst-uncover/UNCOVER_DV_web"
            org.opencontainers.image.source="https://github.com/jwst-uncover/UNCOVER_DV_web"
            org.opencontainers.image.authors="The JWST Uncover Team"
            org.opencontainers.image.revision="${{ github.sha }}"
            org.opencontainers.image.vendor="University of Pittsburgh"
            org.opencontainers.image.ref.name="ghcr.io/jwst-uncover/uncover_dv:${{ github.sha }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          platforms: linux/amd64,linux/arm64

